### ISSUE TITLE
Caching and cookies

### ISSUE THREAD

**Issue by jonscottclark** [filamentgroup/font-loading#10]
I have a question about the final step of your new recommendations to set a cookie and then apply the "fonts-loaded" class immediately to the HTML in order to speed up the font-loading on subsequent page loads.

This seems unreliable to me. How do we know how long to set the cookie for? The amount of time the font files will be cached will be determined by the server's Cache-Control headers, so you'll need to ensure that your cookie's expiry length matches that value. (Right? I'm not 100% sure of this)

Or what if the user decides to clear their cache through their browser, while keeping their cookies intact? With the demo script, the function to get FontFaceObserver to fetch the webfonts would return early, and so the user would have no webfonts _at all_ until they clear their cookies.

Could you elaborate on what other steps you need to take, or things to consider, before employing this optimization?

**Comment by improved-software** [comment]
I think if you set your cookie to a reasonable expiry time it won't be a big concern. (and within any Cache-Control headers you set)

I'm using the font events method that has the @font-face CSS as normal. I've set the cookie to expire in 7 days.

In the unlikely event that a user clears the cache but not the cookies within this time frame, it will just fall back to loading the fonts via @font-face in the normal way, then be cached again.
