### ISSUE TITLE
Test with HTTP2

### ISSUE THREAD

**Issue by zachleat** [filamentgroup/font-loading#2]
Related also #1. Test both methods.

**Comment by icoloma** [comment]
Just to make the question explicit, my biggest concern here is that with HTTP 2.0 browsers should (in theory):
- Download and process the CSS
- Download the HTML file. Detect the use of fonts, download in parallel with the rest.
- Download and process the JavaScript file. This could, or could not, have started before fonts.

`font-loading` would wait until JavaScript is here to start downloading fonts, serializing things. Also, base64 will produce 30% bigger downloads. We will show something sooner, but may also be delaying the arrival of the fonts.

**Comment by scottjehl** [comment]
Our recommended approach has moved to the third example in this repo, which should work very well with http2, given that it uses `font-face` and ordinary font files. Thanks!
