### ISSUE TITLE
Font load fail on Firefox (downloadable font: incorrect file size in WOFF header)

### ISSUE THREAD

**Issue by jepezi** [filamentgroup/font-loading#3]
Hi! I've tried this technique and got it working on Chrome. However, on Firefox, I got the following error in the console and all fonts on the page are the fallback ones.  

downloadable font: incorrect file size in WOFF header..  

Tried googling but it seems like most of the results are not specifically about font embedded as data uri. Any idea?

**Comment by jepezi** [comment]
Never mind. The problem was the online generator (http://dopiaza.org/tools/datauri/index.php). Changed to the one from font provider solves the issue. Not sure why though.  Anyway, thanks for sharing the technique!

**Comment by zachleat** [comment]
Thanks for circling back with an update!
