### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by jacmaes** [filamentgroup/font-loading#4]
Unless I misunderstand part of the latest recommended technique, the HTML markup is different depending on whether a cookie has been set. This means that the page cannot be properly cached, and we all know how important proper caching is for performance.

**Comment by scottjehl** [comment]
You can definitely use strong HTML caching with this approach if you want. The idea with the cookie is that across an entire site (on pages you visit after the first page), you'll get a class sooner to pair with a presumably cached font. 

That said, we don't want to over-emphasize the cookie part. It's a minor improvement on top of the overall workflow. You might also consider placing the font enabling script in the `head` of your page to try and add that class a little sooner. Either way, it's a small optimization. Thanks!
