### ISSUE TITLE
Chrome isn't interpreting the URI fonts properly

### ISSUE THREAD

**Issue by RedOwlWebDesign** [filamentgroup/font-loading#6]
This is ... really odd, so odd that at first I thought it was what you were _trying_ to show.

This is how the demo page for Font Events looks in Chrome 42 on Vista:
![font-events](https://cloud.githubusercontent.com/assets/1918243/7624014/4cc5063e-f9b0-11e4-9743-d822f9c07951.JPG)

This is how the Data URIs page looks:
![font-data-uris](https://cloud.githubusercontent.com/assets/1918243/7624019/62f88a7a-f9b0-11e4-848b-8de97b16786e.JPG)

I only see the messed-up font in Chrome -- the particular mess-up depends on whether I zoom the browser, but something is wrong at every size. 

What's the difference between the URI files and the @font-face files? Whatever is causing this, I want to make sure not to do it!

**Comment by zachleat** [comment]
Ah these were using bad Data URIs! They should have been prefixed `src: url("data:font/woff;charset=utf-8;base64,…` and `src: url("data:font/woff2;charset=utf-8;base64,…`

Fixed now.
