### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by DanielGarzaB** [filamentgroup/font-loading#8]
Im using http://master.origin.font-loading.fgtest.com/data-uris-cookie.html

And now I get this error in chrome:
Failed to decode downloaded font: data:application/font-woff2,

How to fix this?

**Comment by zachleat** [comment]
Ah these were using bad Data URIs! They should have been prefixed `src: url("data:font/woff;charset=utf-8;base64,…` and `src: url("data:font/woff2;charset=utf-8;base64,…`

Fixed now.

Duplicate of #6.
